name: Yamale Validation


on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose the appropriate Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamale

      - name: Run validation
        run: |
          find . -type f -name "config.yaml" -not -path "./config.yaml" > file_list.txt
          validation_failed=false
          while IFS= read -r file; do
            validation_result=""
            if ! validation_result=$(yamale -s schema.yaml "$file" 2>&1); then
              echo "$validation_result"
              validation_failed=true
            fi
          done < file_list.txt
          if [ "$validation_failed" = true ]; then
            echo "Validation failed for one or more files."
            exit 1
          fi
